return {
  -- {
    -- "rebelot/kanagawa.nvim",
    -- build = ":KanagawaCompile",
    -- config = function ()
    --   require("kanagawa").setup({
    --     background = "dragon",
    --     transparent = true,
    --     compile = true,
    --     colors = {
    --       theme = {
    --         all = {
    --           ui = {
    --             bg_gutter = "none"
    --           }
    --         }
    --       }
    --     }
    --   })
    --   vim.cmd.colorscheme "kanagawa-dragon"
    -- end
--   }
}
